### ISSUE TITLE
数据样例

### ISSUE THREAD

**Issue by BarryZM** [SmallVagetable/opinionExtraction#1]
楼主你好呀，请问能发下这个项目的数据样例么？

**Comment by SmallVagetable** [comment]
你好，这个数据是公司里面的，不方便发出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BarryZM <notifications@github.com&gt;
发送时间: 2019年10月10日 14:22
收件人: SmallVagetable/opinionExtraction <opinionExtraction@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SmallVagetable/opinionExtraction] 数据样例 (#1)




楼主你好呀，请问能发下这个项目的数据样例么？

**Comment by SmallVagetable** [comment]
这个数据样例就是
"""
我爱中国。
北京是中国的首都。
国庆节快乐。
"""
这样的一句句的句子的sentence.txt文件

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BarryZM <notifications@github.com>
发送时间: 2019年10月10日 14:22
收件人: SmallVagetable/opinionExtraction <opinionExtraction@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[SmallVagetable/opinionExtraction] 数据样例 (#1)




楼主你好呀，请问能发下这个项目的数据样例么？

**Comment by BarryZM** [comment]
多谢楼主！
